name: Delete abandoned branches

on:
    # Run weekly on Sunday midnight
    schedule:
        - cron: '0 0 * * 0'

    # Allow workflow to be manually run from the GitHub UI
    workflow_dispatch:

jobs:
    cleanup_old_branches:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Configure Git user
              run: |
                git config --global user.name "AbhiChanGit"
                git config --global user.email "abhishek.23.01.2005@gmail.com"

            - name: Get unused Branches
              uses: phpdocker-io/github-actions-delete-abandoned-branches@v2
              id: unused_branches
              with:
                github_token: ${{ github.token }}
                last_commit_age_days: 0
                dry_run: yes

            - name: Create branch for PR
              run: |
                git checkout -b delete-branches-${{ github.sha }}
                git commit --allow-empty -m "Prepare PR for abandoned branch deletion"
                git push origin delete-branches-${{ github.sha }}

            - name: Create pull request for branch deletion with gh CLI
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                # Convert single quotes to double quotes to create valid JSON
                branches_json=$(echo '${{ steps.unused_branches.outputs.deleted_branches }}' | sed "s/'/\"/g")
                
                # Build a Markdown table header
                table="| Branch Name | Last Commit Date | Last Commit Message | Last Updated |\n|-------------|------------------|---------------------|--------------|"
                
                # Iterate over each branch in the JSON array and append a row to the table
                for branch in $(echo "$branches_json" | jq -r '.[]'); do
                  # Replace "Unknown" with dynamic properties if available
                  table="$table\n| $branch | Unknown | Unknown | Unknown |"
                done
                
                # Build the pull request body combining the branch list and the table
                pr_body="This pull request proposes to delete the following abandoned branches:

                $branches_json

                $table"
                    
                echo "$pr_body"  # Optional: print the PR body for debugging
                gh pr create \
                  --title "Delete abandoned branches" \
                  --body "$pr_body" \
                  --base main \
                  --head delete-branches-${{ github.sha }}

                  
            - name: Get output
              run: "echo 'Deleted branches: ${{ steps.unused_branches.outputs.deleted_branches }}'"
